---
title: "Bike Esposure Modeling_UC_Berkeley"
author: "Md Mintu Miah, Ph.D."
date: "2023-01-25"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# read necessary library
rm(list = ls())

if (!require("pacman")) install.packages("pacman")
p_load(dplyr)
p_load(MASS)
p_load(sandwich)
#library(mgcv)
p_load(lmtest)
p_load(caret)
p_load(AER)
p_load(cvTools)
p_load(ggplot2)
p_load(readr)
#library(plyr)
#library(glmmTMB)

```


```{r}
##### FUNCTION DEFINITIONS #####
cvstats <- function (p, k, r=1) {
  n = k * r
  stats <- p %>%
    group_by(Resample) %>%
    summarize(rmse=sqrt(mean((pred - obs) ^ 2)),
              mae=mean(abs(pred - obs)),
              mape=mean(abs((pred - obs) / obs * 100)),
              r2=cor(pred, obs,use="complete.obs")^2,
              mfr2=((sum()))) %>%
    summarize(mean(rmse), se_rmse=sd(rmse)/sqrt(n), mean(mae), 
              se_mae=sd(mae)/sqrt(n), mean(mape), se_mape=sd(mape)/sqrt(n),
              mean(r2), se_r2=sd(r2)/sqrt(n))
  stats
}

cvstats.tertile <- function(p, k, r=1) {
  # Note: assignment is stochastic at boundaries, thus the fractional n's
  n_cv = k * r  # total out of sample predictions
  
  stats <- p %>% 
    mutate(tertile = ntile(obs, 3)) %>%
    group_by(Resample, tertile) %>%
    summarize(rmse=sqrt(mean((pred - obs) ^ 2)),
              mae=mean(abs(pred - obs)),
              mape=mean(abs((pred - obs) / obs * 100)),
              r2=cor(pred, obs, use="complete.obs")^2, n=n()) %>%
    group_by(tertile) %>%
    summarize(mean(rmse), se_rmse=sd(rmse)/sqrt(n_cv), mean(mae), 
              se_mae=sd(mae)/sqrt(n_cv), mean(mape), se_mape=sd(mape)/sqrt(n_cv),
              mean(r2), se_r2=sd(r2)/sqrt(n_cv), n=sum(n)/r)
  
  stats
}

cvstats.county <- function(m, d, k, r) {
  # for now group must be in select var list
  #n_cv = k * r
  
  p2 <- d %>% dplyr::select(rowIndex, matched_seg_id, county, AADB) %>%
    inner_join(m$pred, by="rowIndex") 
  
  n_reg <- p2 %>%
    distinct(rowIndex, county) %>%
    group_by(county) %>%
    summarize(n=n())
  
  stats <- p2 %>% 
    group_by(Resample, county) %>%
    summarize(rmse=sqrt(mean((pred - obs) ^ 2)),
              mae=mean(abs(pred - obs)),
              mape=mean(abs((pred - obs) / obs * 100)),
              ae=mean(pred-obs),
              ape=mean((pred - obs) / obs * 100),
              r2=cor(pred, obs, use="complete.obs")^2,
              n=n()) %>%
    group_by(county) %>%
    summarize(mean(rmse), mean(mae), 
              mean(mape), mean(r2, na.rm=F)) %>%
    left_join(n_reg, by="county")
  
  stats
}

cvstats.pattern <- function(m, d, k, r) {
  # for now group must be in select var list
  p2 <- d %>% dplyr::select(rowIndex, matched_seg_id, county, AADB, Leg) %>%
    inner_join(m$pred, by="rowIndex")
  
  stats <- p2 %>% 
    group_by(Leg) %>%
    summarize(rmse=sqrt(mean((pred - obs) ^ 2)),
              mae=mean(abs(pred - obs)),
              mape=mean(abs((pred - obs) / obs * 100)),
              avgpe=mean((pred - obs) / obs * 100),
              avgerr=mean(pred-obs))
  print(stats)
}

mf_r2 <- function(m) {
  # McFadden's pseudo-R2
  r2 <- 1 - (m$deviance / m$null.deviance)
  r2
}

summarize_model <- function(m, d, k, r, robust_se="HC3") {
  # m - model train/test results from caret package
  # k - number of Cv folds
  # r - number of fold repeats
  p <- m$pred
  print(cvstats(p, k, r))
  print(cvstats.tertile(p, k, r))
  print(cvstats.county(m, d, k, r))
  print(summary(m))
  print("")
  print(paste("McFadden's pseudo-R2 =", mf_r2(m$finalModel)))
  print("")
  print(coeftest(m$finalModel, 
                 vcov = vcovHC(m$finalModel, type=robust_se)))  # robust SEs 
}

plot_regions <- function(m, d, title="", scales="fixed") {
  p2 <- d %>% dplyr::select(rowIndex, matched_seg_id, county, AADB, Leg) %>%
    inner_join(m$pred, by="rowIndex") %>%
    group_by(matched_seg_id, county, Leg) %>%
    summarize(avg_obs=mean(obs), avg_pred=mean(pred))
  
  p2 %>% ggplot(aes(x=avg_pred, y=avg_obs)) +
    geom_point(col="blue") +coord_flip(ylim = c(0,2000), xlim = c(0, 2000))+
    geom_abline(intercept=0, slope=1, lty=2) +
    facet_wrap(~ county, scales=scales) +
    labs(x="mean predicted AADB", y="observed AADB") +
    ggtitle(title)
}


plot_all <- function(m, d, title="", label_outliers=0) {
  # label_outliers - label if avg err falls in top X pct of cases
  p2 <- d %>% dplyr::select(rowIndex, matched_seg_id, county, AADB, Leg,year) %>%
    inner_join(m$pred, by="rowIndex") %>%
    group_by(matched_seg_id,county, Leg, year) %>%
    summarize(avg_obs=mean(obs), avg_pred=mean(pred)) %>%
    mutate(avg_err=mean(avg_pred - avg_obs)) 
    label_min <- quantile(abs(p2$avg_err), p=((100 - label_outliers) / 100))
  
  p2 %>% ggplot(aes(x=avg_pred, y=avg_obs, col=as.factor(county),
                    shape=as.factor(county))) +
    geom_abline(intercept=0, slope=1, lty=2) +
    geom_point(size=2.0, fill=NA) +coord_flip(ylim = c(0,2000), xlim = c(0, 2000))+
    labs(x="mean predicted AADB", y="observed AADB") + 
    geom_text(data=subset(p2, avg_err >= 0 & abs(avg_err) >= label_min),
              aes(avg_pred, avg_obs, label=substr(county, 1, 27)),
              nudge_y=30, size=3) +
    geom_text(data=subset(p2, avg_err < 0 & abs(avg_err) >= label_min),
              aes(avg_pred, avg_obs, label=substr(county, 1, 27)),
              nudge_y=-30, size=3) +
    ggtitle(title)
}


##### END FUNCTION DEFINITIONS #####
```

# read the data
```{r}
data=read.csv('D:/Bike Exposure/Modeling/Final_data_march1.csv')
data=subset(data, data$ATT>0)
data$ATT.in.Thousands <- data$ATT/1000
data$AADB <- round(data$ATT/365, digit=0)
data$rowIndex <- seq.int(nrow(data))
data$primary <- ifelse(data$fclass=='primary', 1, 0)
data$secondary <- ifelse(data$fclass=='secondary', 1, 0)
data$tertiary<- ifelse(data$fclass=='tertiary', 1, 0)
data$residential<- ifelse(data$fclass=='residential', 1, 0)
data$trunk<- ifelse(data$fclass=='trunk', 1, 0)
data$secondary_link<- ifelse(data$fclass=='secondary_link', 1, 0)
data$unclassified<- ifelse(data$fclass=='unclassified', 1, 0)
data$speed_0_25=ifelse(data$speed<=25, 1, 0)
data$speed_21_35=ifelse(dplyr::between(data$speed, 21, 35), 1, 0)
data$speed_greater_than_35=ifelse(data$speed>35, 1, 0)
data$Stv_commute_adb=(data$forward_commute_trip_count+data$reverse_commute_trip_count)/365
data$Stv_leisure_adb=(data$forward_leisure_trip_count+data$reverse_leisure_trip_count)/365
data$Stv_Ave_speed=data$forward_average_speed+data$reverse_average_speed
data$path=ifelse(data$bike_facs=='Class I', 1, 0)
data$bike_lane=ifelse(data$bike_facs=='Class II', 1, 0)
data$bike_route=ifelse(data$bike_facs=='Class III', 1, 0)
data$cycle_track=ifelse(data$bike_facs=='Class IV', 1, 0)
data$trail=ifelse(data$bike_facs=='Class V', 1, 0)
data$trail=ifelse(data$bike_facs=='Class V', 1, 0)
data$Interstate=ifelse(data$fc_draft==1, 1, 0)
data$Freeway=ifelse(data$fc_draft==2, 1, 0)
data$Principal_Arterial=ifelse(data$fc_draft==3, 1, 0)
data$Minor_Arterial=ifelse(data$fc_draft==4, 1, 0)
data$Major_Collector=ifelse(data$fc_draft==5, 1, 0)
data$Minor_Collector=ifelse(data$fc_draft==6, 1, 0)
data$Minor_Local=ifelse(data$fc_draft==7, 1, 0)
#data[is.na(data)] <- 0
write.csv(data,'D:/Bike Exposure/Modeling/Final_data_March5.csv')
head(data,5)
```
`
```{r}
colnames(data)
```






```{r}
unique(data$fclass)
```



```{r}
# save this updated data
#write.csv(u_data1,'D:/Bike Exposure/Modeling/Model_final_data.csv')
```




```{r}
# remove tha columns that have missing value
#data1=data %>% 
#  select(where(~!any(is.na(.))))
num_cols <- unlist(lapply(data, is.numeric)) 
data1 <- data[ , num_cols]  
#data1=data1 %>% dplyr::select(where(is.numeric))
#data1$rowIndex <- seq.int(nrow(data1))
data1
```


```{r}
z=cor(data1)
zdf <- as.data.frame((z))
zdf=subset(zdf,select=c(AADB))
zdf
```




```{r}
# Set up train/test controller 
seed = 94704 
k = 10  # folds
r = 10  # repeats
set.seed(seed)  # note checked fairly stable w/ seed changes

# Note: eventually went back to caret w/ stratified folds 
train_control5 <- trainControl(method="repeatedcv", number=k, repeats=r,
                               savePredictions = TRUE)

```



```{r}
#check volume Bin
quantile(as.integer(data$AADB), p=seq(0, 1, 1/3))
nrow(data)
```


```{r}
colnames(data)
```





```{r}

#datac=subset(data,data$ATT.in.Thousands<1000)
#row.names(datac) <- NULL
```

```{r}
par(mfrow=c(2,3))
plot(data1$pctbiketowork_t, data1$AADB)
plot(data1$pctbiketowork_q, data1$AADB)
plot(data1$pctbiketowork_h, data1$AADB)
plot(data1$totbiketoworkpersqmi_t, data1$AADB)
plot(data1$totbiketoworkpersqmi_q, data1$AADB)
plot(data1$totbiketoworkpersqmi_h, data1$AADB)
```

```{r}
par(mfrow=c(2,3))
plot(data$pctnoveh_t, data$AADB)
plot(data$pctnoveh_q, data$AADB)
plot(data$pctnoveh_h, data$AADB)
plot(data$hshlddensitysqmi_t, data$AADB)
plot(data$hshlddensitysqmi_q, data$AADB)
plot(data$hshlddensitysqmi_h, data$AADB)
```

```{r}
par(mfrow=c(1,3))
plot(data$totwhitepersqmi_t, data$AADB)
plot(data$totwhitepersqmi_q, data$AADB)
plot(data$totwhitepersqmi_h, data$AADB)
#plot(datac$popdensitysqmi_t, datac$ATT)
#plot(datac$popdensitysqmi_q, datac$ATT)
#plot(datac$popdensitysqmi_h, datac$ATT)
```
```{r}
par(mfrow=c(2,3))
plot(data$totwhitepersqmi_t, data$AADB)
plot(data$totwhitepersqmi_q, data$AADB)
plot(data$totwhitepersqmi_h, data$AADB)
plot(data$popdensitysqmi_t, data$AADB)
plot(data$popdensitysqmi_q, data$AADB)
plot(data$popdensitysqmi_h, data$AADB)
```

```{r}
par(mfrow=c(1,3))
plot(data$speed, data$AADB)
plot(data$slope, data$AADB)
plot(data$reverse_average_speed, data$AADB)
#plot(datac$forward_average_speed_2018_h, datac$ATT)
#plot(datac$forward_average_speed_2018_h, datac$ATT)
#plot(datac$reverse_average_speed_2019_h, datac$ATT)
```
```{r}
colnames(data)
```

```{r}
which(is.na(data$AADB))
```


# Static+ Emerging Model
```{r}
# run combined  Static model (only)2016-2019)
set.seed(seed)
m3 <- train(AADB ~Stv_commute_adb+Stv_leisure_adb+pctbiketowork_h
+pctnoveh_h+popdensitysqmi_q+slope+speed_0_25+near_univ_miles+trail
,
            
    #Stv_commute+Stv_leisure+pctbiketowork_q+totatleastbachelorspersqmi_h+log(totnovehpersqmi_h+0.01)+sqrt(hshldden#sitysqmi_t)+tertiary+speed_0_25
                data =data, method = "lm",
                trControl = train_control5, na.action=na.exclude)
#family=sm.families.NegativeBinomial(link=sm.families.links.identity)
#family='poisson
# for nargative Binomial: family="nbinom2"
summarize_model(m3, data, k, r)
plot_regions(m3, data, title="CA Bicycle Exposure Static+Emerging Model", scales="fixed")  # scales="free" or 'fixed' is an option
plot_all(m3, data, title="CA Bicycle Exposure Static+Emerging Model", label_outliers=NA)  # label outliers in top X%, NA turns off labeling
```



